### ISSUE TITLE
Some users have wrong previous rating

### ISSUE THREAD

**Issue by bkhanale** [vsp4/codechef-rating-predictor#2]
Check this person: codechef.com/users/competehere
His initial rating in OCT17 is wrong. Check it out.

**Comment by vsp4** [comment]
Hi, I just checked and it looks fine to me. For user competehere, Overall Rating: 1875, Long Rating: 2064

**Comment by bkhanale** [comment]
Oh. I was confused between overall ratings and long ratings. Everything is fine and nice work btw.
